name: Build & Publish

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"

jobs:
  build:
    strategy:
      matrix:
        node: [ '14', '16', '18', '20', 'latest' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: npm run lint
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.node == 'latest' }}
        with:
          name: dist
          path: dist/

  publish_npm:
    if: github.ref_type == 'tag'
    needs: ["build"]
    runs-on: ubuntu-latest
    environment:
      name: "NPM"
      url: https://www.npmjs.com/package/${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish

  publish_github:
    needs: ["build"]
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    environment:
      name: "GitHub Packages"
      url: https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/pkgs/npm/${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - uses: jossef/action-set-json-field@v2.1
        with:
          file: package.json
          field: name
          value: "@${{ github.repository_owner }}/${{ github.event.repository.name }}"
      - env:
          OWNER: ${{ github.repository_owner }}
          NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          echo "@${OWNER}:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> .npmrc
          cat .npmrc
          npm publish